# Generated by Django 5.2.13 on 2026-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
