# Generated by Django 4.2.30 on 2026-04-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_driverprofile_cancelled_trips_and_more'),
    ]

    operations = []
