# Generated by Django 5.2.13 on 2026-04-25 19:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('en_route', 'En Route'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=32)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_profile', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulances', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
    ]
