# Generated by Django 5.2.13 on 2026-04-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0002_database_design_alignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulance',
            options={'ordering': ['plate_number']},
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
