# Generated by Django 5.2.13 on 2026-04-25 19:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulances', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_type', models.CharField(blank=True, help_text='e.g. cardiac, trauma, accident', max_length=64)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Searching for Ambulance'), ('accepted', 'Ambulance En Route'), ('retrieved', 'Patient picked up'), ('delivered', 'Patient delivered to hospital')], default='pending', max_length=32)),
                ('patient_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('patient_description', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='ambulances.ambulance')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to=settings.AUTH_USER_MODEL)),
                ('selected_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
