# Generated by Django 5.2.13 on 2026-04-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospitalalert_hospitalresourcelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
